from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app) # This allows Carrd to talk to Python

@app.route('/get-quote', methods=['POST'])
def calculate():
    data = request.json
    qty = int(data.get('quantity', 1))
    # Custom Ink Logic: $20 per shirt, $5 extra if they added a photo
    base_price = 20
    photo_fee = 5 if data.get('has_photo') else 0
    
    total = (base_price + photo_fee) * qty
    
    return jsonify({
        "price": f"${total:.2f}",
        "timeline": "10-14 business days",
        "message": "Quote generated by Python Brain"
    })

if __name__ == "__main__":
    app.run()
